---
openapi: 3.0.0
info:
  title: SyskenKnowledge
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/happy663/Syskenknowledge/1.0.0
    description: SwaggerHub API Auto Mocking
tags:
  - name: thread
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /thread/create:
    post:
      tags:
        - thread
      summary: スレッドを立てるAPI
      description: ユーザからスレッド名を受け取ってスレッドを立てる
      operationId: addInventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateThead"
      responses:
        "201":
          description: Inventory item to add
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTheadResponse"
        "400":
          description: invalid input, object invalid

  /thread/delete:
    delete:
      tags:
        - thread
      summary: スレッドを削除するAPI
      description: ユーザ自身が作成したスレッドを削除する
      operationId: addInventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Deleate"
      responses:
        "201":
          description: Inventory item to add
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DleateResponse"
        "400":
          description: invalid input, object invalid
          # produces:
          # - "apllication/json"
          # parameters:
          # - name: "id"
          #   in: "path"
          #   description: "削除対象の商品id"
          #   required: true
          #   type: "integer"
          # responses:
          #   204:
          #     description: "削除の戻り値"

    # delete:
    #   tags:
    #   - "products"
    #   summary: "商品情報削除"
    #   description: "URIで指定したidのproductsテーブルの商品情報を削除する"
    #   produces:
    #   - "apllication/json"
    #   parameters:
    #   - name: "id"
    #     in: "path"
    #     description: "削除対象の商品id"
    #     required: true
    #     type: "integer"
    #   responses:
    #     204:
    #       description: "削除の戻り値"

  /less:
    get:
      tags:
        - less
      summary: レスの情報を受け取るAPI
      description: レスの情報を受け取るAPI
      parameters: []
      responses:
        "200":
          description: invalid input, object invalid
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/SendLess"
                # example:

    post:
      tags:
        - less
      summary: レスを送るAPI
      description: ユーザが入力した内容をスレッドに投稿
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateThead"
      responses:
        "201":
          description: Inventory item to add
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTheadResponse"
        "400":
          description: invalid input, object invalid

components:
  schemas:
    CreateThead:
      required:
        - date
        - ipAddress
        - sentence
        - title
      type: object
      properties:
        title:
          type: string
          example: 今日の朝ごはんについて
        sentence:
          type: string
          example: 今日の朝ごはんの内容が思い出せない助けて
        ipAddress:
          type: string
          format: ipv4
          example: 122.135.235.47
        macAddress:
          type: string
          example: "#EAJOUJASD"
        date:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    CreateTheadResponse:
      required:
        - date
        - id
      type: object
      properties:
        id:
          type: string
          example: ""
        date:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    SendLess:
      required:
        - date
        - ipAddress
        - sentence
      type: object
      properties:
        sentence:
          type: string
          example: まずお昼ご飯が何か思い出そ
        ipAddress:
          type: string
          format: ipv4
          example: 122.135.235.47
        macAddress:
          type: string
          example: "#EAJOUJASD"
        date:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    InventoryItem:
      required:
        - id
        - manufacturer
        - name
        - releaseDate
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        manufacturer:
          $ref: "#/components/schemas/Manufacturer"
    Manufacturer:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: https://www.acme-corp.com
        phone:
          type: string
          example: 408-867-5309

    Deleate:
      required:
        - date
        - ipAddress
        - sentence
        - title
      type: object
      properties:
        title:
          type: string
          example: 朝ごはんについて
        sentence:
          type: string
          example: 朝ごはんの内容が思い出せない助けて
        ipAddress:
          type: string
          format: ipv4
          example: 122.135.235.47
        macAddress:
          type: string
          example: "#EAJOUJASD"
        date:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
