# goバージョン
FROM golang:1.17.2-alpine
# アップデートとgitのインストール！！
RUN apk add --update &&  apk add git
# ワーキングディレクトリの設定
WORKDIR /go/src/app
# ホストのファイルをコンテナの作業ディレクトリに移行
# ADD . /go/src/app
CMD ["go","run","main.go"]